version: '3.4'

secrets:
  pgsql:
    file: ./etc/secrets/pgsql
  pgsql_repl:
    file: ./etc/secrets/pgsql_repl

services:
  server1:
    image: consul:1.2.1
    ports:
     - 8501:8500
    command: "agent -server -retry-join server1 server2 server3 -client 0.0.0.0 -ui -bind '{{ GetInterfaceIP \"eth0\" }}'"
    networks:
      - core
      - pgdb
    deploy:
      replicas: 1
   
     
  server2:
    image: consul:1.2.1
    ports:
     - 8502:8500
    command: "agent -server -retry-join server1 server2 server3 -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    networks:
      - core
      - pgdb
    deploy:
      replicas: 1
    
  server3:
    image: consul:1.2.1
    ports:
     - 8503:8500
    command: "agent -server -retry-join server1 server2 server3 -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    networks:
      - core
      - pgdb
    deploy:
      replicas: 1
   

